matrix:
  include:
    - os: osx
      osx_image: xcode 8.3
      compiler: clang
      script:
       - make -C CS4496P2
    - os: linux
      dist: xenial
      compiler: gcc
      script:
        - make -C CS4496P2
