matrix:
  include:
    - os: osx
      osx_image: xcode 8.3
      compiler: clang
      script:
       - make -C CS4496P2
    - os: linux
      before_install:
       - sudo apt-get install freeglut3-dev
      addons:
        apt:
          update: true
      dist: xenial
      compiler: gcc
      script:
        - make -C CS4496P2
